-- Update PD reminder email template with UNICConnect branding
UPDATE system_settings 
SET value = '{
  "subject": "Action Required: Complete Position Description for {{positionTitle}}",
  "from_name": "UNICConnect",
  "from_email": "recruitment@unicconnect.org",
  "html_body": "<html><body style=\"font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 0;\"><div style=\"background: #2563eb; padding: 30px; text-align: center;\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\"><img src=\"https://cxpnvbphjpntrvvgjhli.lovable.app/assets/UNICC_logo.png\" alt=\"UN Logo\" style=\"height: 50px; vertical-align: middle; margin-right: 15px;\"><span style=\"color: white; font-size: 28px; font-weight: bold; vertical-align: middle;\">UNICConnect</span></td></tr></table></div><div style=\"background: #f9fafb; padding: 30px;\"><p style=\"font-size: 16px; margin-bottom: 20px;\">Dear {{hiringManagerName}},</p><p style=\"margin-bottom: 20px;\">Your initial request for the following position has been approved:</p><div style=\"background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #2563eb;\"><p style=\"margin: 5px 0;\"><strong>📋 Position:</strong> {{positionTitle}}</p><p style=\"margin: 5px 0;\"><strong>📌 Reference:</strong> {{referenceNumber}}</p><p style=\"margin: 5px 0;\"><strong>✅ Approved:</strong> {{approvalDate}}</p></div><p style=\"margin: 20px 0;\">The next step is to complete the full Position Description (PD). Please click below to continue:</p><div style=\"text-align: center; margin: 30px 0;\"><a href=\"{{pdLink}}\" style=\"background: #2563eb; color: white; padding: 14px 32px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold; font-size: 16px;\">Continue Position Description →</a></div><p style=\"color: #666; font-size: 14px; margin-top: 30px;\">If you have any questions about completing the PD, please contact the HR team.</p><p style=\"margin-top: 30px;\">Best regards,<br><strong>UNICConnect</strong></p></div><div style=\"text-align: center; padding: 20px; color: #666; font-size: 12px; background: #f9fafb;\"><p>This is an automated message from UNICConnect</p></div></body></html>",
  "text_body": "Dear {{hiringManagerName}},\\n\\nYour initial request for the following position has been approved:\\n\\n📋 Position: {{positionTitle}}\\n📌 Reference: {{referenceNumber}}\\n✅ Approved: {{approvalDate}}\\n\\nThe next step is to complete the full Position Description (PD). Please visit the following link to continue:\\n\\n{{pdLink}}\\n\\nIf you have any questions about completing the PD, please contact the HR team.\\n\\nBest regards,\\nUNICConnect"
}'::jsonb
WHERE key = 'email_template_pd_reminder';